import React from 'react'

import { ISelections } from 'types/selections'
import { titleCase } from 'utils/titleCase';

export const PrintHeader = (props: { factionName: string }) => {
  return (
    <header className={'text-center mt-5 d-none d-print-block'}>
      <h1>40k Reminders - {titleCase(props.factionName)}</h1>
    </header>
  )
}

export const PrintUnits = (props: { selections: ISelections }) => {
  const { units, detachments, relics, warlordtraits, subfactions } = props.selections
  return (
    <div className={'row text-center mt-5 d-none d-print-block'}>
      <ItemsDisplay name={'Units'} items={units} />
      <ItemsDisplay name={'Detachments'} items={detachments} />
      <ItemsDisplay name={'Relics'} items={relics} />
      <ItemsDisplay name={'WarlordTraits'} items={warlordtraits} />
      <ItemsDisplay name={'Subfactions'} items={subfactions} />
    </div>
  )
}

const ItemsDisplay = (props: { name: string; items: string[] }) => {
  if (!props.items.length) return null
  return (
    <h4>
      <strong>{props.name}:</strong> {props.items.join(' | ')}
    </h4>
  )
}

export const PrintFooter = () => {
  return (
    <footer className={'text-center pb-4 pt-1 d-none d-print-block'}>
      Generated by <strong>40k Reminders</strong>
      <br />
      <strong>daviseford.com/aos-reminders/</strong>
    </footer>
  )
}
