// Phase Stage Types
export type TPhaseStart = 'START_OF_PHASE'
export type TPhaseDuring = 'DURING_PHASE'
export type TPhaseEnd = 'END_OF_PHASE'

// Phase Stage Exports
export const PHASE_START: TPhaseStart = 'START_OF_PHASE'
export const PHASE_DURING: TPhaseDuring = 'DURING_PHASE'
export const PHASE_END: TPhaseEnd = 'END_OF_PHASE'

// Phases
// Psychic
export type TPsychicPhaseStart = 'START_OF_PSYCHIC_PHASE'
export type TPsychicPhase = 'PSYCHIC_PHASE'
export type TPsychicPhaseEnd = 'END_OF_PSYCHIC_PHASE'

// Move
export type TMovementPhaseStart = 'START_OF_MOVEMENT_PHASE'
export type TMovementPhase = 'MOVEMENT_PHASE'
export type TMovementPhaseEnd = 'END_OF_MOVEMENT_PHASE'

// Shooting
export type TShootingPhaseStart = 'START_OF_SHOOTING_PHASE'
export type TShootingPhase = 'SHOOTING_PHASE'
export type TShootingPhaseEnd = 'END_OF_SHOOTING_PHASE'
export type TEnemyShootingPhaseStart = 'START_OF_ENEMY_SHOOTING_PHASE'
export type TEnemyShootingPhase = 'ENEMY_SHOOTING_PHASE'
export type TEnemyShootingPhaseEnd = 'END_OF_ENEMY_SHOOTING_PHASE'

// Charge
export type TChargePhaseStart = 'START_OF_CHARGE_PHASE'
export type TChargePhase = 'CHARGE_PHASE'
export type TChargePhaseEnd = 'END_OF_CHARGE_PHASE'
export type TEnemyChargePhaseStart = 'START_OF_ENEMY_CHARGE_PHASE'
export type TEnemyChargePhase = 'ENEMY_CHARGE_PHASE'
export type TEnemyChargePhaseEnd = 'END_OF_ENEMY_CHARGE_PHASE'

// Fight
export type TFightPhaseStart = 'START_OF_FIGHT_PHASE'
export type TFightPhase = 'FIGHT_PHASE'
export type TFightPhaseEnd = 'END_OF_FIGHT_PHASE'

// Morale
export type TMoralePhaseStart = 'START_OF_MORALE_PHASE'
export type TMoralePhase = 'MORALE_PHASE'
export type TMoralePhaseEnd = 'END_OF_MORALE_PHASE'

export type TPhases = TPsychicPhase | TMovementPhase | TShootingPhase | TChargePhase | TFightPhase | TMoralePhase
export type TPhaseSegments = TPhaseStart | TPhaseDuring | TPhaseEnd

// Phases Exports
export const START_OF_PSYCHIC_PHASE: TPsychicPhaseStart = 'START_OF_PSYCHIC_PHASE'
export const PSYCHIC_PHASE: TPsychicPhase = 'PSYCHIC_PHASE'
export const END_OF_PSYCHIC_PHASE: TPsychicPhaseEnd = 'END_OF_PSYCHIC_PHASE'
export const START_OF_MOVEMENT_PHASE: TMovementPhaseStart = 'START_OF_MOVEMENT_PHASE'
export const MOVEMENT_PHASE: TMovementPhase = 'MOVEMENT_PHASE'
export const END_OF_MOVEMENT_PHASE: TMovementPhaseEnd = 'END_OF_MOVEMENT_PHASE'
export const START_OF_SHOOTING_PHASE: TShootingPhaseStart = 'START_OF_SHOOTING_PHASE'
export const SHOOTING_PHASE: TShootingPhase = 'SHOOTING_PHASE'
export const END_OF_SHOOTING_PHASE: TShootingPhaseEnd = 'END_OF_SHOOTING_PHASE'
export const START_OF_ENEMY_SHOOTING_PHASE: TEnemyShootingPhaseStart = 'START_OF_ENEMY_SHOOTING_PHASE'
export const ENEMY_SHOOTING_PHASE: TEnemyShootingPhase = 'ENEMY_SHOOTING_PHASE'
export const END_OF_ENEMY_SHOOTING_PHASE: TEnemyShootingPhaseEnd = 'END_OF_ENEMY_SHOOTING_PHASE'
export const START_OF_CHARGE_PHASE: TChargePhaseStart = 'START_OF_CHARGE_PHASE'
export const CHARGE_PHASE: TChargePhase = 'CHARGE_PHASE'
export const END_OF_CHARGE_PHASE: TChargePhaseEnd = 'END_OF_CHARGE_PHASE'
export const START_OF_ENEMY_CHARGE_PHASE: TEnemyChargePhaseStart = 'START_OF_ENEMY_CHARGE_PHASE'
export const ENEMY_CHARGE_PHASE: TEnemyChargePhase = 'ENEMY_CHARGE_PHASE'
export const END_OF_ENEMY_CHARGE_PHASE: TEnemyChargePhaseEnd = 'END_OF_ENEMY_CHARGE_PHASE'
export const START_OF_FIGHT_PHASE: TFightPhaseStart = 'START_OF_FIGHT_PHASE'
export const FIGHT_PHASE: TFightPhase = 'FIGHT_PHASE'
export const END_OF_FIGHT_PHASE: TFightPhaseEnd = 'END_OF_FIGHT_PHASE'
export const START_OF_MORALE_PHASE: TMoralePhaseStart = 'START_OF_MORALE_PHASE'
export const MORALE_PHASE: TMoralePhase = 'MORALE_PHASE'
export const END_OF_MORALE_PHASE: TMoralePhaseEnd = 'END_OF_MORALE_PHASE'

// Turn Types
export type TDeploymentStart = 'START_OF_DEPLOYMENT'
export type TDuringDeployment = 'DURING_DEPLOYMENT'
export type TDeploymentEnd = 'END_OF_DEPLOYMENT'
export type TGameStart = 'START_OF_GAME'
export type TBattleroundStart = 'START_OF_BATTLEROUND'
export type TBattleroundDuring = 'DURING_BATTLEROUND'
export type TGameDuring = 'DURING_GAME'
export type TTurnStart = 'START_OF_TURN'
export type TTurnDuring = 'DURING_TURN'
export type TTurnEnd = 'END_OF_TURN'
export type TGameEnd = 'END_OF_GAME'

// Turn Exports
export const START_OF_DEPLOYMENT: TDeploymentStart = 'START_OF_DEPLOYMENT'
export const DURING_DEPLOYMENT: TDuringDeployment = 'DURING_DEPLOYMENT'
export const END_OF_DEPLOYMENT: TDeploymentEnd = 'END_OF_DEPLOYMENT'
export const START_OF_GAME: TGameStart = 'START_OF_GAME'
export const START_OF_BATTLEROUND: TBattleroundStart = 'START_OF_BATTLEROUND'
export const DURING_BATTLEROUND: TBattleroundDuring = 'DURING_BATTLEROUND'
export const DURING_GAME: TGameDuring = 'DURING_GAME'
export const START_OF_TURN: TTurnStart = 'START_OF_TURN'
export const DURING_TURN: TTurnDuring = 'DURING_TURN'
export const END_OF_TURN: TTurnEnd = 'END_OF_TURN'
export const END_OF_GAME: TGameEnd = 'END_OF_GAME'

// Specific Turn Phases
export type TTurnOne_START_OF_TURN = 'TURN_ONE_START_OF_TURN'
export type TTurnOne_DURING_TURN = 'TURN_ONE_DURING_TURN'
export type TTurnOne_START_OF_PSYCHIC_PHASE = 'TURN_ONE_START_OF_PSYCHIC_PHASE'
export type TTurnOne_PSYCHIC_PHASE = 'TURN_ONE_PSYCHIC_PHASE'
export type TTurnOne_END_OF_PSYCHIC_PHASE = 'TURN_ONE_END_OF_PSYCHIC_PHASE'
export type TTurnOne_START_OF_MOVEMENT_PHASE = 'TURN_ONE_START_OF_MOVEMENT_PHASE'
export type TTurnOne_MOVEMENT_PHASE = 'TURN_ONE_MOVEMENT_PHASE'
export type TTurnOne_END_OF_MOVEMENT_PHASE = 'TURN_ONE_END_OF_MOVEMENT_PHASE'
export type TTurnOne_START_OF_SHOOTING_PHASE = 'TURN_ONE_START_OF_SHOOTING_PHASE'
export type TTurnOne_SHOOTING_PHASE = 'TURN_ONE_SHOOTING_PHASE'
export type TTurnOne_END_OF_SHOOTING_PHASE = 'TURN_ONE_END_OF_SHOOTING_PHASE'
export type TTurnOne_START_OF_CHARGE_PHASE = 'TURN_ONE_START_OF_CHARGE_PHASE'
export type TTurnOne_CHARGE_PHASE = 'TURN_ONE_CHARGE_PHASE'
export type TTurnOne_END_OF_CHARGE_PHASE = 'TURN_ONE_END_OF_CHARGE_PHASE'
export type TTurnOne_START_OF_FIGHT_PHASE = 'TURN_ONE_START_OF_FIGHT_PHASE'
export type TTurnOne_FIGHT_PHASE = 'TURN_ONE_FIGHT_PHASE'
export type TTurnOne_END_OF_FIGHT_PHASE = 'TURN_ONE_END_OF_FIGHT_PHASE'
export type TTurnOne_START_OF_MORALE_PHASE = 'TURN_ONE_START_OF_MORALE_PHASE'
export type TTurnOne_MORALE_PHASE = 'TURN_ONE_MORALE_PHASE'
export type TTurnOne_END_OF_MORALE_PHASE = 'TURN_ONE_END_OF_MORALE_PHASE'
export type TTurnOne_END_OF_TURN = 'TURN_ONE_END_OF_TURN'
export type TTurnTwo_START_OF_TURN = 'TURN_TWO_START_OF_TURN'
export type TTurnTwo_DURING_TURN = 'TURN_TWO_DURING_TURN'
export type TTurnTwo_START_OF_PSYCHIC_PHASE = 'TURN_TWO_START_OF_PSYCHIC_PHASE'
export type TTurnTwo_PSYCHIC_PHASE = 'TURN_TWO_PSYCHIC_PHASE'
export type TTurnTwo_END_OF_PSYCHIC_PHASE = 'TURN_TWO_END_OF_PSYCHIC_PHASE'
export type TTurnTwo_START_OF_MOVEMENT_PHASE = 'TURN_TWO_START_OF_MOVEMENT_PHASE'
export type TTurnTwo_MOVEMENT_PHASE = 'TURN_TWO_MOVEMENT_PHASE'
export type TTurnTwo_END_OF_MOVEMENT_PHASE = 'TURN_TWO_END_OF_MOVEMENT_PHASE'
export type TTurnTwo_START_OF_SHOOTING_PHASE = 'TURN_TWO_START_OF_SHOOTING_PHASE'
export type TTurnTwo_SHOOTING_PHASE = 'TURN_TWO_SHOOTING_PHASE'
export type TTurnTwo_END_OF_SHOOTING_PHASE = 'TURN_TWO_END_OF_SHOOTING_PHASE'
export type TTurnTwo_START_OF_CHARGE_PHASE = 'TURN_TWO_START_OF_CHARGE_PHASE'
export type TTurnTwo_CHARGE_PHASE = 'TURN_TWO_CHARGE_PHASE'
export type TTurnTwo_END_OF_CHARGE_PHASE = 'TURN_TWO_END_OF_CHARGE_PHASE'
export type TTurnTwo_START_OF_FIGHT_PHASE = 'TURN_TWO_START_OF_FIGHT_PHASE'
export type TTurnTwo_FIGHT_PHASE = 'TURN_TWO_FIGHT_PHASE'
export type TTurnTwo_END_OF_FIGHT_PHASE = 'TURN_TWO_END_OF_FIGHT_PHASE'
export type TTurnTwo_START_OF_MORALE_PHASE = 'TURN_TWO_START_OF_MORALE_PHASE'
export type TTurnTwo_MORALE_PHASE = 'TURN_TWO_MORALE_PHASE'
export type TTurnTwo_END_OF_MORALE_PHASE = 'TURN_TWO_END_OF_MORALE_PHASE'
export type TTurnTwo_END_OF_TURN = 'TURN_TWO_END_OF_TURN'
export type TTurnThree_START_OF_TURN = 'TURN_THREE_START_OF_TURN'
export type TTurnThree_DURING_TURN = 'TURN_THREE_DURING_TURN'
export type TTurnThree_START_OF_PSYCHIC_PHASE = 'TURN_THREE_START_OF_PSYCHIC_PHASE'
export type TTurnThree_PSYCHIC_PHASE = 'TURN_THREE_PSYCHIC_PHASE'
export type TTurnThree_END_OF_PSYCHIC_PHASE = 'TURN_THREE_END_OF_PSYCHIC_PHASE'
export type TTurnThree_START_OF_MOVEMENT_PHASE = 'TURN_THREE_START_OF_MOVEMENT_PHASE'
export type TTurnThree_MOVEMENT_PHASE = 'TURN_THREE_MOVEMENT_PHASE'
export type TTurnThree_END_OF_MOVEMENT_PHASE = 'TURN_THREE_END_OF_MOVEMENT_PHASE'
export type TTurnThree_START_OF_SHOOTING_PHASE = 'TURN_THREE_START_OF_SHOOTING_PHASE'
export type TTurnThree_SHOOTING_PHASE = 'TURN_THREE_SHOOTING_PHASE'
export type TTurnThree_END_OF_SHOOTING_PHASE = 'TURN_THREE_END_OF_SHOOTING_PHASE'
export type TTurnThree_START_OF_CHARGE_PHASE = 'TURN_THREE_START_OF_CHARGE_PHASE'
export type TTurnThree_CHARGE_PHASE = 'TURN_THREE_CHARGE_PHASE'
export type TTurnThree_END_OF_CHARGE_PHASE = 'TURN_THREE_END_OF_CHARGE_PHASE'
export type TTurnThree_START_OF_FIGHT_PHASE = 'TURN_THREE_START_OF_FIGHT_PHASE'
export type TTurnThree_FIGHT_PHASE = 'TURN_THREE_FIGHT_PHASE'
export type TTurnThree_END_OF_FIGHT_PHASE = 'TURN_THREE_END_OF_FIGHT_PHASE'
export type TTurnThree_START_OF_MORALE_PHASE = 'TURN_THREE_START_OF_MORALE_PHASE'
export type TTurnThree_MORALE_PHASE = 'TURN_THREE_MORALE_PHASE'
export type TTurnThree_END_OF_MORALE_PHASE = 'TURN_THREE_END_OF_MORALE_PHASE'
export type TTurnThree_END_OF_TURN = 'TURN_THREE_END_OF_TURN'
export type TTurnFour_START_OF_TURN = 'TURN_FOUR_START_OF_TURN'
export type TTurnFour_DURING_TURN = 'TURN_FOUR_DURING_TURN'
export type TTurnFour_START_OF_PSYCHIC_PHASE = 'TURN_FOUR_START_OF_PSYCHIC_PHASE'
export type TTurnFour_PSYCHIC_PHASE = 'TURN_FOUR_PSYCHIC_PHASE'
export type TTurnFour_END_OF_PSYCHIC_PHASE = 'TURN_FOUR_END_OF_PSYCHIC_PHASE'
export type TTurnFour_START_OF_MOVEMENT_PHASE = 'TURN_FOUR_START_OF_MOVEMENT_PHASE'
export type TTurnFour_MOVEMENT_PHASE = 'TURN_FOUR_MOVEMENT_PHASE'
export type TTurnFour_END_OF_MOVEMENT_PHASE = 'TURN_FOUR_END_OF_MOVEMENT_PHASE'
export type TTurnFour_START_OF_SHOOTING_PHASE = 'TURN_FOUR_START_OF_SHOOTING_PHASE'
export type TTurnFour_SHOOTING_PHASE = 'TURN_FOUR_SHOOTING_PHASE'
export type TTurnFour_END_OF_SHOOTING_PHASE = 'TURN_FOUR_END_OF_SHOOTING_PHASE'
export type TTurnFour_START_OF_CHARGE_PHASE = 'TURN_FOUR_START_OF_CHARGE_PHASE'
export type TTurnFour_CHARGE_PHASE = 'TURN_FOUR_CHARGE_PHASE'
export type TTurnFour_END_OF_CHARGE_PHASE = 'TURN_FOUR_END_OF_CHARGE_PHASE'
export type TTurnFour_START_OF_FIGHT_PHASE = 'TURN_FOUR_START_OF_FIGHT_PHASE'
export type TTurnFour_FIGHT_PHASE = 'TURN_FOUR_FIGHT_PHASE'
export type TTurnFour_END_OF_FIGHT_PHASE = 'TURN_FOUR_END_OF_FIGHT_PHASE'
export type TTurnFour_START_OF_MORALE_PHASE = 'TURN_FOUR_START_OF_MORALE_PHASE'
export type TTurnFour_MORALE_PHASE = 'TURN_FOUR_MORALE_PHASE'
export type TTurnFour_END_OF_MORALE_PHASE = 'TURN_FOUR_END_OF_MORALE_PHASE'
export type TTurnFour_END_OF_TURN = 'TURN_FOUR_END_OF_TURN'
export type TTurnFive_START_OF_TURN = 'TURN_FIVE_START_OF_TURN'
export type TTurnFive_DURING_TURN = 'TURN_FIVE_DURING_TURN'
export type TTurnFive_START_OF_PSYCHIC_PHASE = 'TURN_FIVE_START_OF_PSYCHIC_PHASE'
export type TTurnFive_PSYCHIC_PHASE = 'TURN_FIVE_PSYCHIC_PHASE'
export type TTurnFive_END_OF_PSYCHIC_PHASE = 'TURN_FIVE_END_OF_PSYCHIC_PHASE'
export type TTurnFive_START_OF_MOVEMENT_PHASE = 'TURN_FIVE_START_OF_MOVEMENT_PHASE'
export type TTurnFive_MOVEMENT_PHASE = 'TURN_FIVE_MOVEMENT_PHASE'
export type TTurnFive_END_OF_MOVEMENT_PHASE = 'TURN_FIVE_END_OF_MOVEMENT_PHASE'
export type TTurnFive_START_OF_SHOOTING_PHASE = 'TURN_FIVE_START_OF_SHOOTING_PHASE'
export type TTurnFive_SHOOTING_PHASE = 'TURN_FIVE_SHOOTING_PHASE'
export type TTurnFive_END_OF_SHOOTING_PHASE = 'TURN_FIVE_END_OF_SHOOTING_PHASE'
export type TTurnFive_START_OF_CHARGE_PHASE = 'TURN_FIVE_START_OF_CHARGE_PHASE'
export type TTurnFive_CHARGE_PHASE = 'TURN_FIVE_CHARGE_PHASE'
export type TTurnFive_END_OF_CHARGE_PHASE = 'TURN_FIVE_END_OF_CHARGE_PHASE'
export type TTurnFive_START_OF_FIGHT_PHASE = 'TURN_FIVE_START_OF_FIGHT_PHASE'
export type TTurnFive_FIGHT_PHASE = 'TURN_FIVE_FIGHT_PHASE'
export type TTurnFive_END_OF_FIGHT_PHASE = 'TURN_FIVE_END_OF_FIGHT_PHASE'
export type TTurnFive_START_OF_MORALE_PHASE = 'TURN_FIVE_START_OF_MORALE_PHASE'
export type TTurnFive_MORALE_PHASE = 'TURN_FIVE_MORALE_PHASE'
export type TTurnFive_END_OF_MORALE_PHASE = 'TURN_FIVE_END_OF_MORALE_PHASE'
export type TTurnFive_END_OF_TURN = 'TURN_FIVE_END_OF_TURN'

// Specific Turn Consts
export const TURN_ONE_START_OF_TURN: TTurnOne_START_OF_TURN = 'TURN_ONE_START_OF_TURN'
export const TURN_ONE_DURING_TURN: TTurnOne_DURING_TURN = 'TURN_ONE_DURING_TURN'
export const TURN_ONE_START_OF_PSYCHIC_PHASE: TTurnOne_START_OF_PSYCHIC_PHASE = 'TURN_ONE_START_OF_PSYCHIC_PHASE'
export const TURN_ONE_PSYCHIC_PHASE: TTurnOne_PSYCHIC_PHASE = 'TURN_ONE_PSYCHIC_PHASE'
export const TURN_ONE_END_OF_PSYCHIC_PHASE: TTurnOne_END_OF_PSYCHIC_PHASE = 'TURN_ONE_END_OF_PSYCHIC_PHASE'
export const TURN_ONE_START_OF_MOVEMENT_PHASE: TTurnOne_START_OF_MOVEMENT_PHASE = 'TURN_ONE_START_OF_MOVEMENT_PHASE'
export const TURN_ONE_MOVEMENT_PHASE: TTurnOne_MOVEMENT_PHASE = 'TURN_ONE_MOVEMENT_PHASE'
export const TURN_ONE_END_OF_MOVEMENT_PHASE: TTurnOne_END_OF_MOVEMENT_PHASE = 'TURN_ONE_END_OF_MOVEMENT_PHASE'
export const TURN_ONE_START_OF_SHOOTING_PHASE: TTurnOne_START_OF_SHOOTING_PHASE = 'TURN_ONE_START_OF_SHOOTING_PHASE'
export const TURN_ONE_SHOOTING_PHASE: TTurnOne_SHOOTING_PHASE = 'TURN_ONE_SHOOTING_PHASE'
export const TURN_ONE_END_OF_SHOOTING_PHASE: TTurnOne_END_OF_SHOOTING_PHASE = 'TURN_ONE_END_OF_SHOOTING_PHASE'
export const TURN_ONE_START_OF_CHARGE_PHASE: TTurnOne_START_OF_CHARGE_PHASE = 'TURN_ONE_START_OF_CHARGE_PHASE'
export const TURN_ONE_CHARGE_PHASE: TTurnOne_CHARGE_PHASE = 'TURN_ONE_CHARGE_PHASE'
export const TURN_ONE_END_OF_CHARGE_PHASE: TTurnOne_END_OF_CHARGE_PHASE = 'TURN_ONE_END_OF_CHARGE_PHASE'
export const TURN_ONE_START_OF_FIGHT_PHASE: TTurnOne_START_OF_FIGHT_PHASE = 'TURN_ONE_START_OF_FIGHT_PHASE'
export const TURN_ONE_FIGHT_PHASE: TTurnOne_FIGHT_PHASE = 'TURN_ONE_FIGHT_PHASE'
export const TURN_ONE_END_OF_FIGHT_PHASE: TTurnOne_END_OF_FIGHT_PHASE = 'TURN_ONE_END_OF_FIGHT_PHASE'
export const TURN_ONE_START_OF_MORALE_PHASE: TTurnOne_START_OF_MORALE_PHASE =
  'TURN_ONE_START_OF_MORALE_PHASE'
export const TURN_ONE_MORALE_PHASE: TTurnOne_MORALE_PHASE = 'TURN_ONE_MORALE_PHASE'
export const TURN_ONE_END_OF_MORALE_PHASE: TTurnOne_END_OF_MORALE_PHASE = 'TURN_ONE_END_OF_MORALE_PHASE'
export const TURN_ONE_END_OF_TURN: TTurnOne_END_OF_TURN = 'TURN_ONE_END_OF_TURN'
export const TURN_TWO_START_OF_TURN: TTurnTwo_START_OF_TURN = 'TURN_TWO_START_OF_TURN'
export const TURN_TWO_DURING_TURN: TTurnTwo_DURING_TURN = 'TURN_TWO_DURING_TURN'
export const TURN_TWO_START_OF_PSYCHIC_PHASE: TTurnTwo_START_OF_PSYCHIC_PHASE = 'TURN_TWO_START_OF_PSYCHIC_PHASE'
export const TURN_TWO_PSYCHIC_PHASE: TTurnTwo_PSYCHIC_PHASE = 'TURN_TWO_PSYCHIC_PHASE'
export const TURN_TWO_END_OF_PSYCHIC_PHASE: TTurnTwo_END_OF_PSYCHIC_PHASE = 'TURN_TWO_END_OF_PSYCHIC_PHASE'
export const TURN_TWO_START_OF_MOVEMENT_PHASE: TTurnTwo_START_OF_MOVEMENT_PHASE = 'TURN_TWO_START_OF_MOVEMENT_PHASE'
export const TURN_TWO_MOVEMENT_PHASE: TTurnTwo_MOVEMENT_PHASE = 'TURN_TWO_MOVEMENT_PHASE'
export const TURN_TWO_END_OF_MOVEMENT_PHASE: TTurnTwo_END_OF_MOVEMENT_PHASE = 'TURN_TWO_END_OF_MOVEMENT_PHASE'
export const TURN_TWO_START_OF_SHOOTING_PHASE: TTurnTwo_START_OF_SHOOTING_PHASE = 'TURN_TWO_START_OF_SHOOTING_PHASE'
export const TURN_TWO_SHOOTING_PHASE: TTurnTwo_SHOOTING_PHASE = 'TURN_TWO_SHOOTING_PHASE'
export const TURN_TWO_END_OF_SHOOTING_PHASE: TTurnTwo_END_OF_SHOOTING_PHASE = 'TURN_TWO_END_OF_SHOOTING_PHASE'
export const TURN_TWO_START_OF_CHARGE_PHASE: TTurnTwo_START_OF_CHARGE_PHASE = 'TURN_TWO_START_OF_CHARGE_PHASE'
export const TURN_TWO_CHARGE_PHASE: TTurnTwo_CHARGE_PHASE = 'TURN_TWO_CHARGE_PHASE'
export const TURN_TWO_END_OF_CHARGE_PHASE: TTurnTwo_END_OF_CHARGE_PHASE = 'TURN_TWO_END_OF_CHARGE_PHASE'
export const TURN_TWO_START_OF_FIGHT_PHASE: TTurnTwo_START_OF_FIGHT_PHASE = 'TURN_TWO_START_OF_FIGHT_PHASE'
export const TURN_TWO_FIGHT_PHASE: TTurnTwo_FIGHT_PHASE = 'TURN_TWO_FIGHT_PHASE'
export const TURN_TWO_END_OF_FIGHT_PHASE: TTurnTwo_END_OF_FIGHT_PHASE = 'TURN_TWO_END_OF_FIGHT_PHASE'
export const TURN_TWO_START_OF_MORALE_PHASE: TTurnTwo_START_OF_MORALE_PHASE =
  'TURN_TWO_START_OF_MORALE_PHASE'
export const TURN_TWO_MORALE_PHASE: TTurnTwo_MORALE_PHASE = 'TURN_TWO_MORALE_PHASE'
export const TURN_TWO_END_OF_MORALE_PHASE: TTurnTwo_END_OF_MORALE_PHASE = 'TURN_TWO_END_OF_MORALE_PHASE'
export const TURN_TWO_END_OF_TURN: TTurnTwo_END_OF_TURN = 'TURN_TWO_END_OF_TURN'
export const TURN_THREE_START_OF_TURN: TTurnThree_START_OF_TURN = 'TURN_THREE_START_OF_TURN'
export const TURN_THREE_DURING_TURN: TTurnThree_DURING_TURN = 'TURN_THREE_DURING_TURN'
export const TURN_THREE_START_OF_PSYCHIC_PHASE: TTurnThree_START_OF_PSYCHIC_PHASE = 'TURN_THREE_START_OF_PSYCHIC_PHASE'
export const TURN_THREE_PSYCHIC_PHASE: TTurnThree_PSYCHIC_PHASE = 'TURN_THREE_PSYCHIC_PHASE'
export const TURN_THREE_END_OF_PSYCHIC_PHASE: TTurnThree_END_OF_PSYCHIC_PHASE = 'TURN_THREE_END_OF_PSYCHIC_PHASE'
export const TURN_THREE_START_OF_MOVEMENT_PHASE: TTurnThree_START_OF_MOVEMENT_PHASE =
  'TURN_THREE_START_OF_MOVEMENT_PHASE'
export const TURN_THREE_MOVEMENT_PHASE: TTurnThree_MOVEMENT_PHASE = 'TURN_THREE_MOVEMENT_PHASE'
export const TURN_THREE_END_OF_MOVEMENT_PHASE: TTurnThree_END_OF_MOVEMENT_PHASE = 'TURN_THREE_END_OF_MOVEMENT_PHASE'
export const TURN_THREE_START_OF_SHOOTING_PHASE: TTurnThree_START_OF_SHOOTING_PHASE =
  'TURN_THREE_START_OF_SHOOTING_PHASE'
export const TURN_THREE_SHOOTING_PHASE: TTurnThree_SHOOTING_PHASE = 'TURN_THREE_SHOOTING_PHASE'
export const TURN_THREE_END_OF_SHOOTING_PHASE: TTurnThree_END_OF_SHOOTING_PHASE = 'TURN_THREE_END_OF_SHOOTING_PHASE'
export const TURN_THREE_START_OF_CHARGE_PHASE: TTurnThree_START_OF_CHARGE_PHASE = 'TURN_THREE_START_OF_CHARGE_PHASE'
export const TURN_THREE_CHARGE_PHASE: TTurnThree_CHARGE_PHASE = 'TURN_THREE_CHARGE_PHASE'
export const TURN_THREE_END_OF_CHARGE_PHASE: TTurnThree_END_OF_CHARGE_PHASE = 'TURN_THREE_END_OF_CHARGE_PHASE'
export const TURN_THREE_START_OF_FIGHT_PHASE: TTurnThree_START_OF_FIGHT_PHASE = 'TURN_THREE_START_OF_FIGHT_PHASE'
export const TURN_THREE_FIGHT_PHASE: TTurnThree_FIGHT_PHASE = 'TURN_THREE_FIGHT_PHASE'
export const TURN_THREE_END_OF_FIGHT_PHASE: TTurnThree_END_OF_FIGHT_PHASE = 'TURN_THREE_END_OF_FIGHT_PHASE'
export const TURN_THREE_START_OF_MORALE_PHASE: TTurnThree_START_OF_MORALE_PHASE =
  'TURN_THREE_START_OF_MORALE_PHASE'
export const TURN_THREE_MORALE_PHASE: TTurnThree_MORALE_PHASE = 'TURN_THREE_MORALE_PHASE'
export const TURN_THREE_END_OF_MORALE_PHASE: TTurnThree_END_OF_MORALE_PHASE =
  'TURN_THREE_END_OF_MORALE_PHASE'
export const TURN_THREE_END_OF_TURN: TTurnThree_END_OF_TURN = 'TURN_THREE_END_OF_TURN'
export const TURN_FOUR_START_OF_TURN: TTurnFour_START_OF_TURN = 'TURN_FOUR_START_OF_TURN'
export const TURN_FOUR_DURING_TURN: TTurnFour_DURING_TURN = 'TURN_FOUR_DURING_TURN'
export const TURN_FOUR_START_OF_PSYCHIC_PHASE: TTurnFour_START_OF_PSYCHIC_PHASE = 'TURN_FOUR_START_OF_PSYCHIC_PHASE'
export const TURN_FOUR_PSYCHIC_PHASE: TTurnFour_PSYCHIC_PHASE = 'TURN_FOUR_PSYCHIC_PHASE'
export const TURN_FOUR_END_OF_PSYCHIC_PHASE: TTurnFour_END_OF_PSYCHIC_PHASE = 'TURN_FOUR_END_OF_PSYCHIC_PHASE'
export const TURN_FOUR_START_OF_MOVEMENT_PHASE: TTurnFour_START_OF_MOVEMENT_PHASE = 'TURN_FOUR_START_OF_MOVEMENT_PHASE'
export const TURN_FOUR_MOVEMENT_PHASE: TTurnFour_MOVEMENT_PHASE = 'TURN_FOUR_MOVEMENT_PHASE'
export const TURN_FOUR_END_OF_MOVEMENT_PHASE: TTurnFour_END_OF_MOVEMENT_PHASE = 'TURN_FOUR_END_OF_MOVEMENT_PHASE'
export const TURN_FOUR_START_OF_SHOOTING_PHASE: TTurnFour_START_OF_SHOOTING_PHASE = 'TURN_FOUR_START_OF_SHOOTING_PHASE'
export const TURN_FOUR_SHOOTING_PHASE: TTurnFour_SHOOTING_PHASE = 'TURN_FOUR_SHOOTING_PHASE'
export const TURN_FOUR_END_OF_SHOOTING_PHASE: TTurnFour_END_OF_SHOOTING_PHASE = 'TURN_FOUR_END_OF_SHOOTING_PHASE'
export const TURN_FOUR_START_OF_CHARGE_PHASE: TTurnFour_START_OF_CHARGE_PHASE = 'TURN_FOUR_START_OF_CHARGE_PHASE'
export const TURN_FOUR_CHARGE_PHASE: TTurnFour_CHARGE_PHASE = 'TURN_FOUR_CHARGE_PHASE'
export const TURN_FOUR_END_OF_CHARGE_PHASE: TTurnFour_END_OF_CHARGE_PHASE = 'TURN_FOUR_END_OF_CHARGE_PHASE'
export const TURN_FOUR_START_OF_FIGHT_PHASE: TTurnFour_START_OF_FIGHT_PHASE = 'TURN_FOUR_START_OF_FIGHT_PHASE'
export const TURN_FOUR_FIGHT_PHASE: TTurnFour_FIGHT_PHASE = 'TURN_FOUR_FIGHT_PHASE'
export const TURN_FOUR_END_OF_FIGHT_PHASE: TTurnFour_END_OF_FIGHT_PHASE = 'TURN_FOUR_END_OF_FIGHT_PHASE'
export const TURN_FOUR_START_OF_MORALE_PHASE: TTurnFour_START_OF_MORALE_PHASE =
  'TURN_FOUR_START_OF_MORALE_PHASE'
export const TURN_FOUR_MORALE_PHASE: TTurnFour_MORALE_PHASE = 'TURN_FOUR_MORALE_PHASE'
export const TURN_FOUR_END_OF_MORALE_PHASE: TTurnFour_END_OF_MORALE_PHASE =
  'TURN_FOUR_END_OF_MORALE_PHASE'
export const TURN_FOUR_END_OF_TURN: TTurnFour_END_OF_TURN = 'TURN_FOUR_END_OF_TURN'
export const TURN_FIVE_START_OF_TURN: TTurnFive_START_OF_TURN = 'TURN_FIVE_START_OF_TURN'
export const TURN_FIVE_DURING_TURN: TTurnFive_DURING_TURN = 'TURN_FIVE_DURING_TURN'
export const TURN_FIVE_START_OF_PSYCHIC_PHASE: TTurnFive_START_OF_PSYCHIC_PHASE = 'TURN_FIVE_START_OF_PSYCHIC_PHASE'
export const TURN_FIVE_PSYCHIC_PHASE: TTurnFive_PSYCHIC_PHASE = 'TURN_FIVE_PSYCHIC_PHASE'
export const TURN_FIVE_END_OF_PSYCHIC_PHASE: TTurnFive_END_OF_PSYCHIC_PHASE = 'TURN_FIVE_END_OF_PSYCHIC_PHASE'
export const TURN_FIVE_START_OF_MOVEMENT_PHASE: TTurnFive_START_OF_MOVEMENT_PHASE = 'TURN_FIVE_START_OF_MOVEMENT_PHASE'
export const TURN_FIVE_MOVEMENT_PHASE: TTurnFive_MOVEMENT_PHASE = 'TURN_FIVE_MOVEMENT_PHASE'
export const TURN_FIVE_END_OF_MOVEMENT_PHASE: TTurnFive_END_OF_MOVEMENT_PHASE = 'TURN_FIVE_END_OF_MOVEMENT_PHASE'
export const TURN_FIVE_START_OF_SHOOTING_PHASE: TTurnFive_START_OF_SHOOTING_PHASE = 'TURN_FIVE_START_OF_SHOOTING_PHASE'
export const TURN_FIVE_SHOOTING_PHASE: TTurnFive_SHOOTING_PHASE = 'TURN_FIVE_SHOOTING_PHASE'
export const TURN_FIVE_END_OF_SHOOTING_PHASE: TTurnFive_END_OF_SHOOTING_PHASE = 'TURN_FIVE_END_OF_SHOOTING_PHASE'
export const TURN_FIVE_START_OF_CHARGE_PHASE: TTurnFive_START_OF_CHARGE_PHASE = 'TURN_FIVE_START_OF_CHARGE_PHASE'
export const TURN_FIVE_CHARGE_PHASE: TTurnFive_CHARGE_PHASE = 'TURN_FIVE_CHARGE_PHASE'
export const TURN_FIVE_END_OF_CHARGE_PHASE: TTurnFive_END_OF_CHARGE_PHASE = 'TURN_FIVE_END_OF_CHARGE_PHASE'
export const TURN_FIVE_START_OF_FIGHT_PHASE: TTurnFive_START_OF_FIGHT_PHASE = 'TURN_FIVE_START_OF_FIGHT_PHASE'
export const TURN_FIVE_FIGHT_PHASE: TTurnFive_FIGHT_PHASE = 'TURN_FIVE_FIGHT_PHASE'
export const TURN_FIVE_END_OF_FIGHT_PHASE: TTurnFive_END_OF_FIGHT_PHASE = 'TURN_FIVE_END_OF_FIGHT_PHASE'
export const TURN_FIVE_START_OF_MORALE_PHASE: TTurnFive_START_OF_MORALE_PHASE =
  'TURN_FIVE_START_OF_MORALE_PHASE'
export const TURN_FIVE_MORALE_PHASE: TTurnFive_MORALE_PHASE = 'TURN_FIVE_MORALE_PHASE'
export const TURN_FIVE_END_OF_MORALE_PHASE: TTurnFive_END_OF_MORALE_PHASE =
  'TURN_FIVE_END_OF_MORALE_PHASE'
export const TURN_FIVE_END_OF_TURN: TTurnFive_END_OF_TURN = 'TURN_FIVE_END_OF_TURN'

// When
export type TTurnWhen =
  | TDeploymentStart
  | TDuringDeployment
  | TDeploymentEnd
  | TGameStart
  | TGameDuring
  | TBattleroundStart
  | TTurnStart
  | TTurnEnd
  | TGameEnd
  | TPsychicPhaseStart
  | TPsychicPhase
  | TPsychicPhaseEnd
  | TMovementPhaseStart
  | TMovementPhase
  | TMovementPhaseEnd
  | TShootingPhaseStart
  | TShootingPhase
  | TShootingPhaseEnd
  | TChargePhaseStart
  | TChargePhase
  | TChargePhaseEnd
  | TFightPhaseStart
  | TFightPhase
  | TFightPhaseEnd
  | TMoralePhaseStart
  | TMoralePhase
  | TMoralePhaseEnd
  | TEnemyShootingPhaseStart
  | TEnemyShootingPhase
  | TEnemyShootingPhaseEnd
  | TEnemyChargePhaseStart
  | TEnemyChargePhase
  | TEnemyChargePhaseEnd
  | TTurnOne_START_OF_TURN
  | TTurnOne_DURING_TURN
  | TTurnOne_START_OF_PSYCHIC_PHASE
  | TTurnOne_PSYCHIC_PHASE
  | TTurnOne_END_OF_PSYCHIC_PHASE
  | TTurnOne_START_OF_MOVEMENT_PHASE
  | TTurnOne_MOVEMENT_PHASE
  | TTurnOne_END_OF_MOVEMENT_PHASE
  | TTurnOne_START_OF_SHOOTING_PHASE
  | TTurnOne_SHOOTING_PHASE
  | TTurnOne_END_OF_SHOOTING_PHASE
  | TTurnOne_START_OF_CHARGE_PHASE
  | TTurnOne_CHARGE_PHASE
  | TTurnOne_END_OF_CHARGE_PHASE
  | TTurnOne_START_OF_FIGHT_PHASE
  | TTurnOne_FIGHT_PHASE
  | TTurnOne_END_OF_FIGHT_PHASE
  | TTurnOne_START_OF_MORALE_PHASE
  | TTurnOne_MORALE_PHASE
  | TTurnOne_END_OF_MORALE_PHASE
  | TTurnOne_END_OF_TURN
  | TTurnTwo_START_OF_TURN
  | TTurnTwo_DURING_TURN
  | TTurnTwo_START_OF_PSYCHIC_PHASE
  | TTurnTwo_PSYCHIC_PHASE
  | TTurnTwo_END_OF_PSYCHIC_PHASE
  | TTurnTwo_START_OF_MOVEMENT_PHASE
  | TTurnTwo_MOVEMENT_PHASE
  | TTurnTwo_END_OF_MOVEMENT_PHASE
  | TTurnTwo_START_OF_SHOOTING_PHASE
  | TTurnTwo_SHOOTING_PHASE
  | TTurnTwo_END_OF_SHOOTING_PHASE
  | TTurnTwo_START_OF_CHARGE_PHASE
  | TTurnTwo_CHARGE_PHASE
  | TTurnTwo_END_OF_CHARGE_PHASE
  | TTurnTwo_START_OF_FIGHT_PHASE
  | TTurnTwo_FIGHT_PHASE
  | TTurnTwo_END_OF_FIGHT_PHASE
  | TTurnTwo_START_OF_MORALE_PHASE
  | TTurnTwo_MORALE_PHASE
  | TTurnTwo_END_OF_MORALE_PHASE
  | TTurnTwo_END_OF_TURN
  | TTurnThree_START_OF_TURN
  | TTurnThree_DURING_TURN
  | TTurnThree_START_OF_PSYCHIC_PHASE
  | TTurnThree_PSYCHIC_PHASE
  | TTurnThree_END_OF_PSYCHIC_PHASE
  | TTurnThree_START_OF_MOVEMENT_PHASE
  | TTurnThree_MOVEMENT_PHASE
  | TTurnThree_END_OF_MOVEMENT_PHASE
  | TTurnThree_START_OF_SHOOTING_PHASE
  | TTurnThree_SHOOTING_PHASE
  | TTurnThree_END_OF_SHOOTING_PHASE
  | TTurnThree_START_OF_CHARGE_PHASE
  | TTurnThree_CHARGE_PHASE
  | TTurnThree_END_OF_CHARGE_PHASE
  | TTurnThree_START_OF_FIGHT_PHASE
  | TTurnThree_FIGHT_PHASE
  | TTurnThree_END_OF_FIGHT_PHASE
  | TTurnThree_START_OF_MORALE_PHASE
  | TTurnThree_MORALE_PHASE
  | TTurnThree_END_OF_MORALE_PHASE
  | TTurnThree_END_OF_TURN
  | TTurnFour_START_OF_TURN
  | TTurnFour_DURING_TURN
  | TTurnFour_START_OF_PSYCHIC_PHASE
  | TTurnFour_PSYCHIC_PHASE
  | TTurnFour_END_OF_PSYCHIC_PHASE
  | TTurnFour_START_OF_MOVEMENT_PHASE
  | TTurnFour_MOVEMENT_PHASE
  | TTurnFour_END_OF_MOVEMENT_PHASE
  | TTurnFour_START_OF_SHOOTING_PHASE
  | TTurnFour_SHOOTING_PHASE
  | TTurnFour_END_OF_SHOOTING_PHASE
  | TTurnFour_START_OF_CHARGE_PHASE
  | TTurnFour_CHARGE_PHASE
  | TTurnFour_END_OF_CHARGE_PHASE
  | TTurnFour_START_OF_FIGHT_PHASE
  | TTurnFour_FIGHT_PHASE
  | TTurnFour_END_OF_FIGHT_PHASE
  | TTurnFour_START_OF_MORALE_PHASE
  | TTurnFour_MORALE_PHASE
  | TTurnFour_END_OF_MORALE_PHASE
  | TTurnFour_END_OF_TURN
  | TTurnFive_START_OF_TURN
  | TTurnFive_DURING_TURN
  | TTurnFive_START_OF_PSYCHIC_PHASE
  | TTurnFive_PSYCHIC_PHASE
  | TTurnFive_END_OF_PSYCHIC_PHASE
  | TTurnFive_START_OF_MOVEMENT_PHASE
  | TTurnFive_MOVEMENT_PHASE
  | TTurnFive_END_OF_MOVEMENT_PHASE
  | TTurnFive_START_OF_SHOOTING_PHASE
  | TTurnFive_SHOOTING_PHASE
  | TTurnFive_END_OF_SHOOTING_PHASE
  | TTurnFive_START_OF_CHARGE_PHASE
  | TTurnFive_CHARGE_PHASE
  | TTurnFive_END_OF_CHARGE_PHASE
  | TTurnFive_START_OF_FIGHT_PHASE
  | TTurnFive_FIGHT_PHASE
  | TTurnFive_END_OF_FIGHT_PHASE
  | TTurnFive_START_OF_MORALE_PHASE
  | TTurnFive_MORALE_PHASE
  | TTurnFive_END_OF_MORALE_PHASE
  | TTurnFive_END_OF_TURN
  | TBattleroundDuring
  | TTurnDuring
